language: python
python:
  - "3.7"

os: linux
dist: bionic

# miller on ubuntu bionic is 5.3 we need 5.4
# addons:
#   apt:
#     packages:
#       - miller
#       - bats

notifications:
  email: false

install:
  # - bats --version
  # - mlr --version
  - pip install goodtables

script:
  - goodtables validate csv/datapackage.json
  # old referential integrity checks
  # - bats --tap test/*.bats
