language: python
python:
  - "3.7"

os: linux
dist: bionic

# miller on ubuntu bionic is 5.3 we need 5.4 or higher
addons:
  apt:
    packages:
      - miller
      - bats
      - textql

notifications:
  email: false


install:
  - pip install goodtables csvkit

before_script:
  - mlr --version
  - textql --version

# Checks
script:
  - goodtables validate csv/datapackage.json
  # - bats --tap test/*.bats

# Generate Views
after_success:
   - textql -output-file csv/views/view1.csv -header -sql "select distinct a.act_id, a.act_object, ps.title from Act a, PrimarySource ps inner join PrimarySource on a.act_object = ps.prim_source_id  where ps.title_lang = a.id_lang and a.act_object!='W0414'"  csv/data/*.csv
